/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "business": {
        "AUTH": {
            "AUTH_ERR_001": string;
            "AUTH_ERR_002": string;
            "AUTH_ERR_003": string;
        };
        "ROL": {
            "ROL_ERR_001": string;
            "ROL_ERR_002": string;
            "ROL_ERR_003": string;
            "ROL_ERR_004": string;
        };
        "LGI": {
            "LGI_ERR_001": string;
            "LGI_ERR_002": string;
            "LGI_ERR_003": string;
        };
    };
    "system": {
        "EXH": {
            "EXH_ERR_001": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
