/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "business": {
        "AUTH": {
            "AUTH_ERR_001": string;
            "AUTH_ERR_002": string;
            "AUTH_ERR_003": string;
        };
        "ROL": {
            "ROL_ERR_001": string;
            "ROL_ERR_002": string;
            "ROL_ERR_003": string;
            "ROL_ERR_004": string;
        };
        "LGI": {
            "LGI_ERR_001": string;
            "LGI_ERR_002": string;
            "LGI_ERR_003": string;
            "LGI_ERR_004": string;
        };
        "REG": {
            "REG_ERR_001": string;
            "REG_ERR_002": string;
            "REG_ERR_003": string;
            "REG_ERR_004": string;
            "REG_ERR_005": string;
            "REG_ERR_006": string;
            "REG_ERR_007": string;
            "REG_ERR_008": string;
            "REG_ERR_009": string;
            "REG_ERR_010": string;
            "REG_ERR_011": string;
            "REG_ERR_012": string;
            "REG_ERR_013": string;
        };
        "VRE": {
            "VRE_ERR_001": string;
            "VRE_ERR_002": string;
            "VRE_ERR_003": string;
            "VRE_ERR_004": string;
            "VRE_ERR_005": string;
        };
        "CHP": {
            "CHP_ERR_001": string;
            "CHP_ERR_002": string;
            "CHP_ERR_003": string;
            "CHP_ERR_004": string;
            "CHP_ERR_005": string;
            "CHP_ERR_006": string;
            "CHP_ERR_007": string;
            "CHP_ERR_008": string;
        };
        "FGP": {
            "FGP_ERR_001": string;
            "FGP_ERR_002": string;
            "FGP_ERR_003": string;
            "FGP_ERR_004": string;
            "FGP_ERR_005": string;
            "FGP_ERR_006": string;
            "FGP_ERR_007": string;
            "FGP_ERR_008": string;
            "FGP_ERR_009": string;
            "FGP_ERR_010": string;
        };
        "PRF": {
            "PRF_ERR_001": string;
        };
    };
    "internal": {
        "USER": {
            "USER_ERR_001": string;
            "USER_ERR_002": string;
            "USER_ERR_003": string;
            "USER_ERR_004": string;
            "USER_ERR_005": string;
            "USER_ERR_006": string;
            "USER_ERR_007": string;
            "USER_ERR_008": string;
            "USER_ERR_009": string;
            "USER_ERR_010": string;
            "USER_ERR_011": string;
            "USER_ERR_012": string;
            "USER_ERR_013": string;
            "USER_ERR_014": string;
            "USER_ERR_015": string;
            "USER_ERR_016": string;
            "USER_ERR_017": string;
        };
    };
    "system": {
        "EXH": {
            "EXH_ERR_001": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
